# Generated by Django 3.0.5 on 2020-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reception_code', models.IntegerField(max_length=32, unique=True, verbose_name=' کد پذیرش ')),
                ('reception_date', models.DateField(max_length=32, verbose_name=' تاریخ پذیرش ')),
                ('answer_date', models.DateField(max_length=32, verbose_name='تاریخ پاسخ')),
                ('tests_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='فایل آزمایش')),
                ('response_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='فایل پاسخ')),
                ('Appendix_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='فایل ضمیمه')),
                ('deliver_sample', models.BooleanField(verbose_name='تحویل نمونه')),
                ('response', models.BooleanField(verbose_name='پاسخ')),
                ('approve_response', models.BooleanField(verbose_name='تایید پاسخ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
