# Generated by Django 3.0.5 on 2020-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtests', '0002_auto_20200425_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtest',
            name='approve_response',
            field=models.BooleanField(default=False, verbose_name='تایید پاسخ'),
        ),
        migrations.AlterField(
            model_name='mtest',
            name='deliver_sample',
            field=models.BooleanField(default=False, verbose_name='تحویل نمونه'),
        ),
        migrations.AlterField(
            model_name='mtest',
            name='response',
            field=models.BooleanField(default=False, verbose_name='پاسخ'),
        ),
    ]
